version: '3.9'
services:
  bet_maker:
    build: 
      context: .
    ports:
      - "9056:8000"
    env_file:
      - ./config/conf.env
    volumes:
      - .:/app
    container_name: bet_maker
    command: /bin/bash -c "alembic upgrade head && uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - bets
      - shared

networks:
  bets:
    external: true
  shared:
    external: true