"""initial migrations

Revision ID: 93dce18788d4
Revises: 
Create Date: 2024-12-24 22:58:51.645002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93dce18788d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_event', sa.Integer(), nullable=True),
    sa.Column('bet_sum', sa.Float(), nullable=True),
    sa.Column('coefficient', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'TEAM_1_WINS', 'TEAM_2_WINS', name='status'), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bets')
    # ### end Alembic commands ###
